### PR TITLE
Add fallback for filename from Content-Disposition

### PR DESCRIPTION
**Pull request by codebude**
Just added a fallback for filename retrieval from Content-Disposition after I saw [issue 7](https://github.com/engswee/equalize-xpi-modules/issues/7). Unfortunately I couldn't produce enough test cases, so it would be nice if you could trigger [Robert](https://people.sap.com/robert.warde4) to run a quick test.

### CODE REVIEW

**Review by engswee — CHANGES_REQUESTED** [review]
The logic does not seem right. The else statement introduce for (nameIndex == -1) actually means the name is found in the Content-Type.

Additionally, for Content-Disposition, it looks like the "proper" name is in the "filename=" parameter instead of the "name=" parameter.

Ideally, I think the logic should be:-
i) Check for "name=" parameter in content-type. Add log that filename is being search here. If found, get the substring
ii) Otherwise, check for "filename=" parameter in content-disposition. Add log that filename wasn't found in (i) so searched here instead. If found get the substring
iii) Otherwise, log warning that unable to retrieve from content type or content disposition, and return default
iv) Do the stripping/cleanup if either (i) or (ii) was successful

**Comment by codebude** [comment]
Hi @engswee ,

sorry, I was a little bit tired yesterday. I should have better slept a night over the code and did a review before creating the pull request. All your points sound valid. I'll do a rewrite and add another Pull Request. (I hope this is the right way. Or how to update a pull request which was markes for "requested changes"?)

**Comment by codebude** [comment]
I added you requested changes and think the code is fine now. But just let me hear what you think about it.

In addition I want to mention that with this changes only one (even if it's the more common) part of the Content-Disposition header will be handled. Per specification there is another way the filname could be written to the Content-Disposition header. The second method is via "filename*=" attribute. (https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition) 

But since the code changes ask for **indexOf("filename=")**, the filename*= representation wouldn't break the code. It just won't be handled. So for this reason I think that it's ok to merge the changes, because the simple Content-Disposition handling is still an improvement compared to the current Content-Type only solution.

If someone feels free to implement the "filename*="-handling, he should keep in mind that there can be three types of representation (See chapter 3.2.2 in [RFC5987](https://tools.ietf.org/html/rfc5987)):

1. filename*=%c2%a3%20and%20%e2%82%ac%20rates
2. filename*=UTF-8''%c2%a3%20and%20%e2%82%ac%20rates
3. filename*=UTF-8'en'%c2%a3%20and%20%e2%82%ac%20rates

So to handle the filename* attribute, it would be required to parse (maybe by regex), the encoding, the language and the name and then decode it in dependency to the given encoding. Since this requires more imports (regex, url ecoding, ...) I don't like to implement it, without discussing it with you,  @engswee .

**Review by engswee — CHANGES_REQUESTED** [review]
Overall looks great, just a few changes to keep the code lean.

The substring extraction of the filename need not be encapsulated in else {}. If the filename is in either of the headers, then if(nameIndex == -1) check would be false and it would automatically proceed to the next line of code. If filename is not in both the headers, then it will hit the "return defaultFileName" statement and exit the function.

**Comment by engswee** [comment]
Rafael,

First things first - no apologies are needed. Thanks for the great work and your willingness to collaborate, I'm really grateful for that.

The latest code looks good and I think "should" work. I just added a few comments in my review, it's just because of my preference for lean codes.
else

Regarding your comment on the Content-Disposition, to be honest, I wasn't aware of the "filename*=" myself - it was a good read.

My inclination is not to over complicate the logic with the "filename*=" handling, unless it comes to the point where that becomes the norm rather than the exception. Adding more complexity for something with limited use case doesn't seem worthwhile at the moment.

By the way, another interesting note when I went through SAP Note 856599 (Mail Adapter FAQ) is that the filename in the Content Type is discouraged, and instead Content Disposition is the way to go. It mentions a few RFC references - but well, who bothers to follow standards anyway!!!

**Comment by codebude** [comment]
Hi Eng Swee,

thanks for the feedback. I'm a little bit confused. You write:

> The substring extraction of the filename need not be encapsulated in else {} [...]

But isn't the substring function already in the else block? And if both indexOf-checks get -1, the default filename ist set and the function returned. So I don't see what's wrong.

Or do you talk about the "double"/nested if-else statement? Do you prefer to check first, if any filename exist and if not, to return the defaultname before further processing?

**Comment by engswee** [comment]
Hi Rafael

Sorry for being not clear enough. Even I got part of it wrong actually (see, it's always good to have at least two pairs of eyes!)

The inner (second one for content dispo) substring statement do not need to be in an else {}, it can just be immediately after the if{}.

For the case where filename is not in content type, but in content disposition, it will enter the first if{}, and  not the second if{}.

I'm replying from my mobile so can't get an image for it. If it's not clear, I'll reply again later when I get back home.
________________________________

**Comment by codebude** [comment]
Hi Eng Swee,

at first, let me repeat your words: "no apologies are needed". No reason to say sorry. ;-)

> The inner (second one for content dispo) substring statement do not need to be in an else {}, it can just be immediately after the if{}.

Ok, I see that. The else-branch isn't reached, when there is no filename, because the if-branch has a return. So the inner else isn't necessary. I removed it and send a commit.

**Review by engswee — APPROVED** [review]
Great stuff! Thanks for all the changes

**Comment by engswee** [comment]
Hi @codebude 

I've merged the changes and pulled it into my NWDS local copy.

Looks like it needs an import statement for java.util.Set. Was it okay at your end without the import statement?

**Comment by codebude** [comment]
That's strange... I had this import. Really don't know why it isn't inside the commit. 

spectacle zt7066

**Comment by engswee** [comment]
I had a look at the class in your public repository and the import is also not there. Maybe something was missed between pushing the commit from your local repository to GitHub.

import

Don't worry about it, I will fix this on my end

**Pull request merged**
