### PR TITLE
Fix QoS "EOIO"

### PR DESCRIPTION
**Pull request by codebude**
For proper function of EOIO quality of service, it is necessary to set
sequencyId. Added sequenceId parameter to AttachmentSplitterBean and
implemented sequenceId support in message dispatcher.

### CODE REVIEW

**Comment by engswee** [comment]
Thanks again for your effort in fixing this. I admit I didn't get around to test it out for EOIO. I'll be away for a week so I'll get around to releasing the changes when I'm back.

**Comment by codebude** [comment]
No problem. Have a nice stay.

**Comment by codebude** [comment]
One more clue - even if the sequenceId is type of String, there are some restrictions by the SAP PI system. The sequenceId has to be between 1 and 16 characters long and all characters have to be in uppercase. Maybe you can take care of that in the documentation.

I didn't implement a check for this, because I couldn't do more than throwing an exception. But this isn't possible, because PI system throws an exception itself with a clearly speaking error text.

**Comment by engswee** [comment]
Thanks for the clue. Can you share a screenshot of the error that PI throws? I'll update the documentation based on that.

**Comment by codebude** [comment]
Sure... is that ok? --> http://i.imgur.com/M2tcYua.png

**Comment by engswee** [comment]
Excellent! Thanks!

**Pull request merged**
