### PR TITLE
New feature and a few changes

### PR DESCRIPTION
**Pull request by jvandborg**
Hi Eng,

I've made a minor change to use the CPAFactory to get the LookupManager instead of directly accessing it. This is as per the documentation provided in Javadocs.

Also I've added a feature to make it possible to configure which row to create header fields from.

And last, but not least I've changed the regular expression used to condense the header field names, so it only allows valid characters for XML-tags.

Best regards,
Jacob

### CODE REVIEW

**Comment by engswee** [comment]
Hi Jacob

Thank you for your effort to collaborate on this repository. I have gone through your changes and here are my comments:-

i) LookupManager - thanks providing feedback on this to change it according to the recommended approach. It looks and works fine and I'm okay to incorporate this.

ii) Header row - My guess is that you want to use the field names from a row that is not the first in the Excel sheet. This is a good idea. However, you need to also adjust which row is should start processing from if the header row is not the first row, i.e. if header row is second row in sheet, process data should be from third row onwards. Therefore rowOffset needs to be adjusted accordingly. Also the corresponding audit log message needs to be adjusted accordingly.

iii) XML valid characters - The intention of the regex replacement was just for a simple compression of whitespaces. If we want to replace invalid XML characters, regex expression [^A-Za-z0-9] is not sufficient (for example underscore is a valid XML character). I actually have a class that checks for this (com.equalize.xpi.util.converter.XMLChar), but this was created later than Excel2XMLTransformer, so I haven't gotten around to refactor it to include XML character validation. If you want to add this feature, then I'd suggest you make use of that class. Additionally, as all these changes will be considered minor revision, we need to preserve backwards compatibility for the changes. This means that whatever XML character validation should be optional and controlled by a parameter.

Thanks again for this. Can you please make the required changes for (i) and (ii) and include the new commits into this pull request?

Best regards
Eng Swee

**Comment by jvandborg** [comment]
Hi Eng Swee,

Thanks for you valuable input. I've worked a bit on iii) and would like to put the logic of stripping invalid characters into a method, but I'm having doubts on where to put the method. My initial thought was to put it into XMLChar class. Would this work for you?

Best regards,
Jacob

**Comment by engswee** [comment]
Hi Jacob

Thanks for your reply. I want to reiterate again that I really appreciate your effort in collaborating on this project and improving it.

Regarding your question, yes, I think having a static public method in the XMLChar class will be fine since it's related to valid XML characters. Further to this, I just want to share with you that in ConversionDOMOutput's generateElementName() method, there is a logic that uses the XMLChar class to escape or mangle invalid characters. If you want to have more than just a simple "replace with blank" approach, you can consider moving that to the XMLChar class (I should have probably done that when I created the logic, but I didn't think about it then, sorry about that).

Another thing, since you will be performing the stripping, can you refactor the variable condensedName to something more appropriate since it will no longer just be white-space condensed.

Regards
Eng Swee

**Comment by jvandborg** [comment]
Hi Eng Swee,

It's my pleasure to collaborate on this project. You've done extraordenary work in bringing really useful, generic adapter modules into an easy configurable way.

I've finished implementing the new features as per your request to ensure backwards compatibility. Also I've included documentation for the new parameters in the commit comments. If you need more information I will be more than happy to provide it to you.

Looking forward to hearing from you for feedback.

Best regards,
Jacob

**Comment by engswee** [comment]
Hi Jacob

Just a quick one to say I'm already out of the office, so will only look into this next week. Thanks again for your hard work.

Regards
Eng Swee

**Comment by jvandborg** [comment]
Hi Eng Swee,

No worries. Have a great weekend. Talk to you next week.

Best regards,
Jacob

**Comment by engswee** [comment]
Hi Jacob

I've gone through the latest changes and also tested them out. Overall, I have no concerns with the changes except those in the retrieveModuleParameters() method of Excel2XMLTransformer.java.

Here are my comments:
i) Explicit check for positive integer is not required as it is already done in the getIntParameter() method.
ii) extractSheetContents() method will display the starting row of processing, so it is not required to add an audit log message in retrieveModuleParameters().
iii) My thoughts are not to have the additional rowOffsetFromHeaderRow parameter so that it does not over-complicate the possible combinations of configuration. Having three parameters (rowOffset, headerRow, and rowOffsetFromHeaderRow) means there could be up to 8 combination of these values and might lead to potential bugs. I'm thinking of just having two parameters (rowOffset and headerRow), both of which always count from the first row of the sheet. When rowOffset is zero, it will automatically be skipped to the row after the header row. But when both rowOffset and headerRow are not zero, it is up to the user to configure it correctly so that rowOffset is larger than headerRow. Below is a sample of how I imagine the code to be. Hoping this simplifies both programming and module configuration.
header

Let me know what your thoughts are especially on item (iii) so that we can nail down all these changes.

Regards
Eng Swee

**Comment by jvandborg** [comment]
Hi Eng Swee,

Thanks for you comments. I agree with you in regards to keeping things simple and have changed the code accordingly.

Also I've removed the checks for positive integers. I was not aware that it was already checked in getIntParameter().

In regards to the if-statement checking for headerRow >= rowOffset I've simplified it as I don't see any need for checking if rowOffset != 0 and headerRow != 0.

Looking forward hearing your comments.

Best regards,
Jacob

**Comment by engswee** [comment]
You are absolutely right on the redundant checks for rowOffset and headerRow. :)

Thanks. Everything looks great now. I've merged the pull request and will work on publishing a new release with all of your changes.

Thanks again for your collaboration efforts.

**Comment by jvandborg** [comment]
Thanks Eng Swee. It was a pleasure collaborating with you. :)

If you need help in maintaining some of the parts in the modules, feel free to reach out to me.

**Pull request merged**
